apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: demo-classroom-task
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: demo-classroom-task
              image: alexc/classroomdemotask:latest # alexc/classroomdemotask:latest
              imagePullPolicy: Never
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1